### ISSUE TITLE
PDF: implement text extraction

### ISSUE THREAD

**Issue by wrharris** [GaloisInc/daedalus#133]
Eval3 will evaluate our ability of our parser to extract text from PDF's. In order to do this, we need to:
* identify all of the means for storing text in a PDF and parse them so that their semantic value contains the text. There are at least some means for doing this in Content Streams;
* extract text in the presence of font definitions (Kudu has dropped a hint that this will be evaluated)

**Comment by wrharris** [comment]
Extracted text should be encoded in UTF-8. This amounts to parsing Content Streams by maintaining a map character codes to UTF-8 characters. This map is
* initialized by the resource dictionary in scope 
* updated by content stream operations that update the font.

The notion of relevant "character code" itself is defined by the font in scope. "Composite fonts" are defined over two-byte character codes.

To extract a map from character codes to Unicode chars, we'll need to parse CMap's (#136).

**Comment by wrharris** [comment]
update: `pdf-hs-driver` now outputs the exact bytes that are given as arguments to text-showing operations. The main open issues are to maintain a map from character codes to UTF-8 characters and use it to render text, as discussed above. There is a nearly-complete CMap parser at `spec/CMap.ddl` that can be used to achieve this.

**Comment by mtullsen** [comment]
I'm looking at mods in both driver/Main.hs and the pdf-cos/spec/PdfExtractText.ddl to get this to the "next level".
FYI, here's where we stand now with respect to other tools:
```
================== pdftotext input.pdf - =================

The quick brown fox jumps over the lazy dog’s back.
fi ff fl ffi ffl
yes–no—maybe.
“double quoted”

1

================== pdf-hs-driver --text =================

INFO - tests/td00.pdf at 0 - Catalog (page tree) result:
INFO - tests/td00.pdf at 0 - "The quic k bro wn fo x jumps o v er the lazy dog's bac k.\FS \ESC \GS \RS \USy es\NAKno\SYNma y b e.\DLEdouble quoted\DC11"

================== mutool draw -F text input.pdf =================

Th e q u i c k
b r o wn
f o x
j u m
p s o v e r t h e l a z y
d o g ’ s b a c k .
fi
ff
fl
ffi
ffl
y e s – n o —
m
a y b e .
“ d o u b l e q u o t e d ”

1

================== pdf2txt.py input.pdf =================

The quick brown fox jumps over the lazy dog’s back.
ﬁ ﬀ ﬂ ﬃ ﬄ
yes–no—maybe.
“double quoted”

1
```

**Comment by wrharris** [comment]
Text extraction isn't fully supported, but we have a baseline and makes more sense to track further progress in separate issues.
