### ISSUE TITLE
codegen generates code that fails to drive Eq, Ord, Show

### ISSUE THREAD

**Issue by wrharris** [GaloisInc/daedalus#138]
A recent commit in the branch `extract-text` has a commit <https://github.com/GaloisInc/daedalus/commit/2d3e69d1706ff1786df30f6823502d6def76e85d> in which the DDL spec typechecks, but results in Haskell code that doesn't typecheck. The cause is derivations of `Eq`, `Ord`, and `Show` that fail.

A suspicious feature of the spec is that introduces a DDL type (`sepLists2`) with fields that shadow those of another type (`Pair`). This was unintended, and in fact the issue can be coded around by annotating `sepLists2` to return a `Pair`. Creating this issue as a note so that the underlying issue can be fixed.

**Comment by yav** [comment]
This should be fixed in pull request with T138 in the name
