### ISSUE TITLE
panic during generation of c++ parser code

### ISSUE THREAD

**Issue by reiniert** [GaloisInc/daedalus#153]
With the attached DDL definition, I am able to interpret my input with  `daedalus --interp`.  Generation of the C++ parser code fails though:

```
$ daedalus TransportMessage.ddl --compile-c++ --out-dir=ddl_out
You have encountered a bug in Daedalus's implementation.
*** Please create an issue at https://github.com/GaloisInc/daedalus/issues

%< --------------------------------------------------- 
  Revision:  UNKNOWN
  Branch:    UNKNOWN
  Location:  Non-variable subst in Call
  Message:   
CallStack (from HasCallStack):
  panic, called at src/Daedalus/Panic.hs:17:9 in daedalus-utils-0.1.0.0-2c605a0407d1e31d409a97a17b20397737ecc8f98fd8668f717d9d650460f3dd:Daedalus.Panic
  panic, called at src/Daedalus/Type/Subst.hs:295:32 in daedalus-0.1.0.0-4c618e3eb1e0199fd36ede25a736a03399adb96673b1c0a3699f4625b798af57:Daedalus.Type.Subst
%< --------------------------------------------------- 
```

**Comment by reiniert** [comment]
(Had to rename them to have the `.txt` extension for GitHub to accept them)
[DataMessage.ddl.txt](https://github.com/GaloisInc/daedalus/files/6832129/DataMessage.ddl.txt)
[Stdlib.ddl.txt](https://github.com/GaloisInc/daedalus/files/6832130/Stdlib.ddl.txt)
[TransportMessage.ddl.txt](https://github.com/GaloisInc/daedalus/files/6832131/TransportMessage.ddl.txt)

**Comment by yav** [comment]
It looks like despite the "panic" this is not quite a bug, but rather something we haven't quite implemented yet.   The source grammar uses a parser parameter that is itself parameterized, namely `AppParser` and we do not support this yet in the backends that require specialization, and C++ is one of those.

I'll leave this open as this is something we'd probably like to support, and shouldn't be too hard to do, I think.

In the mean time, this grammar might be a good candidate for being rewritten using the relatively new "implicit parameters" feature, which I think should work OK with the C++ backend.

**Comment by reiniert** [comment]
Thanks @yav.  Do you have any documentation or example that illustrates the "implicit parameters" feature you mentioned?

**Comment by yav** [comment]
There was nothing in the manual, but I just made an example, that I will add to the manual (https://galoisinc.github.io/daedalus/).
In the mean time here is the example, let me know if something doesn't make sense:
```daedalus
{- An "implicit parameter" is a parameter that is automatically
passed along by the system, which helps avoid clutter in specifications.
In Daedalus, implicit parameters have names staring with `?`, for example
`?bigendian`.

Implicit parameters are useful in situations where the value of a parameter
is set once for a given scope, and then the same parameter is just passed
along with no changes to the "leaves" of the spec.   This is quite common
in situations where some configration optoins are read once, and then
are just passed along for the rest of a parser. -}

-- `joinWords` has an implicit parameter called `bigendian`
def joinWords a b =
  if ?bigendian     -- ?bigendian is an implicit parameter
    then a # b
    else b # a

-- Parsers automatically inherit the implicit parameters needed by parsers
-- they use.  Thus, `Word16` and `Word32` also have an implicit parameter
-- called `?bigendian`.
def Word16 = joinWords UInt8 UInt8
def Word32 = joinWords Word16 Word16

-- If a block provides a value for an implicit parameter, then all calls
-- for the rest of the block will use that value for the parmeter.
-- For example, `BEWord16` *does not* have an implicit parameter:
def BEWord16 =
  block
    let ?bigendian = true
    Word16    -- ?bigendian has the value `true`

-- A bigger example where we use big endian parsing in one part of the
-- code, and little endian parsing in another part:
def Main =
  block
    SetStream (arrayStream (concat [ [0,1,0,0,0,1]
                                   , [1,0,1,0,0,0] ]))

    big =
      -- Here we define the value of an implicit parameter
      -- in all uses for the rest of the block
      block
        let ?bigendian = true
        x = Word16
        y = Word32
    little =
      -- This block uses a different value for the implicit parameter
      block
        let ?bigendian = false
        x = Word16
        y = Word32

-- Try it:
-- daedalus example.ddl --run


{-
{ big: { x: 1[16]
       , y: 1[32]
       }
, little: { x: 1[16]
          , y: 1[32]
          }
}
-}
```

**Comment by reiniert** [comment]
Hi @yav, I am using the following snippet:
```
515 def Message PayloadData =
516   block
517     let ?orig = 0
518     let ?cdr1 = false
519     header = Header
520     submessages = Many (Submessage PayloadData)
521     END
```
When I try to parse my data using this definition, I get the following error:
```
./DataMessage.ddl:517:9--517:13: Undefined implicit parameter ?cdr1
```
What does that mean here?

**Comment by reiniert** [comment]
Hmm, maybe the problem is that I am not using that particular implicit parameter `?cdr1` anywhere in this module. But I am using it in an imported module. Also, when I remove this `let` definition, the parsing completes unexpectedly, without ever any value being assigned to `cdr1` (even though its value is tested in one of the parsers in the imported module).

**Comment by reiniert** [comment]
I have reduced this to a small example that shows similar behavior.
```
def joinWords a b = 
  if ?bigendian     -- ?bigendian is an implicit parameter
    then a # b
    else b # a

def Word16 = joinWords UInt8 UInt8
def Word32 = joinWords Word16 Word16

def Main =
  block
    let ?bigendian = true
    SetStream (arrayStream (concat [ [0,1,0,0,0,1]
                                   , [1,0,1,0,0,0] ]))

    big =
      -- Here we define the value of an implicit parameter
      -- in all uses for the rest of the block
      block
        let ?bigendian = true
        x = Word16
        y = Word32
```
Commenting out one of the two `let`s will make the error go away. Is that expected?

**Comment by yav** [comment]
The two examples are a bit different.  In both cases, it is trying to say that you are providing an implicit that doesn't exist, but the "non-existence" is for different reasons.

In the first case, I am guessing that neither `Header` nor `Submessage` have such parameter and I suspect that `?cdr` is supposed to be for `PayloadData`?  In that case, it might be better to not define it in `message`, but rather at the call site of message.   So the call site might look something like this:
```
def MyConcretePayload = ... uses ?cdr ...

def Example =
  block
     let ?cdr = false
     Message MyConcretePayload
```
In general implicit parameters work best in situations where you specify them once at the top level, and then they'd be automatically propagated to the leaves where they are needed.

To see what's going here, the following version is equivalent but uses explicit parameters:
```
def MyConcretePayload cdr = ... uses cdr ...

def Example =
   block
      let cdr = false
      Message (MyConcretePayload cdr)
```

So basically, what's happening is that instead of passing the parameterized payload, we pass the payload with its parameters already applied.  This is how we work around the issue that, at the moment, we don't support parser parameters, that are parameterized (it doesn't matter if those parameters are implicit or explicit).


The issue in the second example is that the implicit parameter is defined twice in the same scope.  Perhaps the error message could be better in that case.  What's happening is that the inner `?bigendian` defines the value of the implicit parameter, and so the outer `let` results in an error because we are providing a parameter that no one has (because it has already been defined).  This might be more obvious if we name the inner block like this:
```
def Main =
  block
    let ?bigendian = true    -- This is an error because nothing uses this parameter
    SetStream (arrayStream (concat [ [0,1,0,0,0,1]
                                   , [1,0,1,0,0,0] ]))

    big = Big

-- Note that Big has no parameters (explicit or implicit)
def Big =
     block
        let ?bigendian = true
        x = Word16
        y = Word32
```

**Comment by reiniert** [comment]
Thanks for explaining, I got it now.

The root cause of my issue was that I was not using `cdr1` anywhere, even though I had defined a parser that uses it. I did not realize I never invoked that parser.

**Comment by yav** [comment]
Great!  

I am considering making a slight change in the syntax, where parsers that access the value of an implicit parameter would have to add it to their parameter list, so `joinWords` from the above example would look like this.

```
def joinWords ?bigendian a b = 
  if ?bigendian     -- ?bigendian is an implicit parameter
    then a # b
    else b # a
```

I think this might make it more obvious where these parameters come from, as they seem a bit magical at the moment... Do you have any thoughts on that?

**Comment by reiniert** [comment]
This might make it slightly more obvious where the parameters come from, but it does not help that much in the big picture. The insight is lost at the level of any parsers invoking this parser, or any level above that. I started adding this information as comment with every parser, but it got tedious pretty quickly. I can not think of any fundamental solution to this. Maybe adding some verbosity flag when invoking `daedalus` that reports the implicit parameters used by each parser, either directly, or indirectly via parsers it invokes.

I do think that there is some room for improvement in the diagnostics coming out of `daedalus`. In your original example, imagine making a typo in the `let` statement, like `let ?bigedian = false`. The result will be an error:
```
$ daedalus Implicit.ddl --run
./Implicit.ddl:24:13--24:21: Undefined implicit parameter ?bigedian
```
I would expect a message along the lines of "Unused parameter `bigedian`", which would be a warning and not an error.

Then removing the entire `let` statement (just to get past that original error) causes this message:
```
$ daedalus Implicit.ddl --run
BUG: not enough args for Name { nameScopedIdent = ModScope "Implicit" "Main", nameContext = AGrammar, nameRange = SourceRange {sourceFrom = SourcePos {sourceIndex = 187, sourceLine = 9, sourceColumn = 5, sourceFile = "./Implicit.ddl"}, sourceTo = SourcePos {sourceIndex = 190, sourceLine = 9, sourceColumn = 8, sourceFile = "./Implicit.ddl"}}, nameID = GUID {getGUID = 3} }
CallStack (from HasCallStack):
  error, called at src/Daedalus/Interp.hs:837:7 in daedalus-0.1.0.0-4c618e3eb1e0199fd36ede25a736a03399adb96673b1c0a3699f4625b798af57:Daedalus.Interp
```
That is where I would expect an error indeed, but now with the message "Undefined implicit parameter `?bigendian`". I can see where this current message comes from, especially keeping your newly proposed parameterlist in mind, but it could be pretty hard to figure out for users without that background information.
