### ISSUE TITLE
optimize the build system

### ISSUE THREAD

**Issue by wrharris** [GaloisInc/daedalus#164]
The build system has been carefully tuned to cope with bottlenecks that have emerged at various points in the process. Currently, making a small change to a near-top-level spec in `extract-text` (e.g., `PdfExtractText.ddl`) results in a 4min build time. We need to:
1. determine if this overhead is inherent;
2. if not, optimize the build system accordingly.

**Comment by mtullsen** [comment]
I'm creating a few different large test ddl files (absractions of and variants of GlyphList.hs) to measure where we are really at in terms of both ddl->hs compile times and hs->obj compile times.

**Comment by wrharris** [comment]
Some further ideas from today's TA2 weekly:
* if it helps, we could certainly split up the current `pdf-cos` into multiple libraries, in particular ones for Unicode, fonts, and content streams. This could just be good organization in its own right, but it also may simplify some build system that's checking for which files are actually edited.
* inspired by that idea, I checked and editing a file in `pdf-driver/spec` still causes a 1m37s build on my machine, without apparently doing anything with `pdf-cos`. This seems suspicious given that `pdf-driver/spec` contains only three `.ddl` files at a total of 292 LoC.

**Comment by mtullsen** [comment]
@wrharris : for daedalus to generate a Haskell file, it still loads and compiles *all* it's dependents, even ones in the pdf-cos/spec/ directory!  This is what is taking some time.  daedalus does not have separate compilation.

**Comment by mtullsen** [comment]
@yav I don't know if there's a way to possibly load a ddl file without compiling its dependent modules?  Just type check the dependents?

**Comment by mtullsen** [comment]
After a bit of exploring, our really long compile time seems to be NOT about separate compilation, not about tons of `Literal n typevar` constraints, or etc but the essence appears to be in compiling arrays.  See #166

**Comment by mtullsen** [comment]
We have a workaround for the moment: I found the sweet spot for the daedalus compile speed of GlyphList.ddl, see commit c39d44c.  We're back to near instantaneous daedalus compiles. @wrharris do we want to close this? The above commit solves the short term problem, and I think #166 would address the longer term problem.

**Comment by wrharris** [comment]
I feel like supporting separate generation of daedalus would be a good thing to have in principle, but given that we've found other solutions for taming build times, I'm fine with closing this one.
