### ISSUE TITLE
Generating C++ for unbiased choice fails

### ISSUE THREAD

**Issue by benoitrazet** [GaloisInc/daedalus#235]
Here is a minimal example to reproduce
```
def Main = Event

def Event =
  Choose {
    voiceMessage = VoiceMessages;
    modeMessage  = {};
  }

def VoiceMessages = {}
```

The error message is the following on MacOS compiling with Apple clang version 12.0.0 (clang-1200.0.31.1)
```
g++ -I. --std=c++17 -Wall -Wno-uninitialized -O3 -o parser main_parser.cpp main.cpp -lgmpxx -lgmp
main_parser.cpp:147:22: error: use of undeclared identifier 'ret_z28zz29z'
    { Event_5_ra0u = ret_z28zz29z;
                     ^
1 error generated.
```

Toggling between `Choose` and `Choose1` for the error to show up. But also inlining the call to `VoiceMessages` with `{}`

**Comment by yav** [comment]
The problem here was that the "capture" analysis incorrectly labelled blocks that are used for returning from functions.   The block needs to match the "capture-status" of the functions from which we are returning, *not* the calling function.
