### ISSUE TITLE
Problem with AES 4 decryption

### ISSUE THREAD

**Issue by yav** [GaloisInc/daedalus#263]
See file `fbf2a234a370fd4d067d38e8411842a326167c92bd42356b4c96368117211535` in `ddl-design` chat

**Comment by yav** [comment]
Here is the actual file:

[fbf2a234a370fd4d067d38e8411842a326167c92bd42356b4c96368117211535.pdf](https://github.com/GaloisInc/daedalus/files/8535286/fbf2a234a370fd4d067d38e8411842a326167c92bd42356b4c96368117211535.pdf)

**Comment by glguy** [comment]
54e5b1a50a4816cedc48cfd5eabb0552f3413f42 avoids attempting to decrypt xref streams
