### ISSUE TITLE
Specializer not reusing definitions

### ISSUE THREAD

**Issue by yav** [GaloisInc/daedalus#27]
It would appear that reusing definitions is not working quite as expected.   I noticed it when specializing `PdfValue.Value`, the output contains the following duplicates, for example:
```
PdfValue.When__14 (x6 : PdfValue.Number) (sign1 : PdfValue.Sign) : Grammar PdfValue.Number =
  do do sign1 is pos
        pure {}
     ($$9 : PdfValue.Number) <- pure x6
     pure $$9
.
PdfValue.When__15 (x5 : PdfValue.Number) (sign : PdfValue.Sign) : Grammar PdfValue.Number =
  do do sign is neg
        pure {}
     ($$8 : PdfValue.Number) <- pure x5
     pure $$8
```

The issue might be that we are missing some cases in the unification code, or maybe we need to do alpha renaming on the instances?

**Comment by simonjwinwood** [comment]
We check for (funcall, args) when doing duplicate detection.  It is (remotely) possible that you can get the same function via 2 different combos of (fun, args), but I doubt that is what is happening here.  It is more likely to be a bug.

**Comment by simonjwinwood** [comment]
```sign1 is pos``` vs ```sign1 is neg```
