### ISSUE TITLE
Improve error-handling for undefined implicit parameters

### ISSUE THREAD

**Issue by samcowger** [GaloisInc/daedalus#285]
Attempting to execute a parser with undefined implicit parameters yields a somewhat unhelpful, uncaught error:

```
def joinWords a b = if ?bigEndian then a # b else b # a
def UInt16 = joinWords UInt8 UInt8
def Main = UInt16
```

produces (when invoked as `daedalus run main.ddl`, with or without input)

```
BUG: not enough args for Name { nameScopedIdent = ModScope "main" "Main", nameContext = AGrammar, nameRange = SourceRange {sourceFrom = SourcePos {sourceIndex = 95, sourceLine = 3, sourceColumn = 5, sourceFile = "./main.ddl"}, sourceTo = SourcePos {sourceIndex = 98, sourceLine = 3, sourceColumn = 8, sourceFile = "./main.ddl"}}, nameID = GUID {getGUID = 2} }
CallStack (from HasCallStack):
  error, called at src/Daedalus/Interp.hs:963:7 in ddls-0.1.0.0-7aa8a0f4:Daedalus.Interp
```

A couple things here:
- Daedalus gladly typechecks this[^1], treating `Main` as a parser expecting to inherit an implicit parameter. I wonder whether it would be wise to introduce a `Main`-specific restriction to detect this issue statically. I'm new to Daedalus, so forgive me if this has already been considered.
- If that's not in order, I would at least prefer to see a runtime error more along the lines of "implicit parameter `bigEndian` undefined" (ideally with a use site and/or context).

[^1]: `daedalus show-types main.ddl` yields, _inter alia_,
    ```
    def Main:
      implict parameter: ?bigEndian : bool
      defines: parser of uint 16
    ```

**Comment by yav** [comment]
The problem here is not implicit parameters per se, but parsers with any parameters (possibly including type parameters, not sure if we fixed that one). I'll make a pass to handle these situations properly and report them as user errors rather than panics.

**Comment by samcowger** [comment]
Thanks!
