### ISSUE TITLE
feature: add case expression for destructing unions and comparing literals

### ISSUE THREAD

**Issue by simonjwinwood** [GaloisInc/daedalus#29]
From the chat:

Simon Winwood 3:06 PM

I suppose we could comma separate pattern cases

case v of {
   Foo x, Bar x, Baz x -> ...;
}

Iavor Diatchki 3:07 PM
Maybe:  case e of { P1 -> e1; P2 -> e2 }.  

I'd avoid the union patterns

Simon Winwood 3:07 PM
main reason I want them is that they are used in NITF pretty heavily

(I think)

do we know the type of v when checking e.g. case?

Iavor Diatchki 3:08 PM
Ah, if we have use case that's OK.  Is the semantics that case e of { P1,P2 -> e} is equivalent to case e of { P1 -> e; P2 -> e}?

Simon Winwood 3:09 PM
yes

that is how it would be in TC

Iavor Diatchki 3:10 PM
We don't know the type because it might not exist yet.   I think you can type-check this in a similar way to the way is for union works (i.e., emit constraints) and it should be able to build the type on its own, or complain

Simon Winwood 3:10 PM
perhaps TCDestUnion :: [(TCName Value, TC a k)] -> TCF a k

Iavor Diatchki 3:11 PM
I think we'd definately want a version of the case statemetn that works on literals

Simon Winwood 3:11 PM
yeah, but that would be either desugared to <| or have another ctor in TC

Iavor Diatchki 3:11 PM
so case e of { 1 -> e1; 2 -> e2 }

Yeah, I guess that makes sense

(we should have a constructor)

Simon Winwood 3:12 PM
and you could maybe do case e of { 1, 2, 3 -> e1 ; _ -> e2 }

Iavor Diatchki 3:12 PM
yes, that seems nice

**Comment by simonjwinwood** [comment]
```case e of { ...``` -> ```case e is { ... ```

**Comment by yav** [comment]
This is somewhat functional now, so I'll close this.  We have other tickets for outstanding tasks related to `cases`
