### ISSUE TITLE
`formats/http/Lexemes.ddl` `hexdig` definition doesn't match RFC 5234

### ISSUE THREAD

**Issue by kenballus** [GaloisInc/daedalus#316]
The hexdig definition in `formats/http/Lexemes.ddl`:
```
def $hexdig   = $digit | 'A' .. 'F' | 'a' .. 'f'
```

The HEXDIG definition in RFC 5234:
```
HEXDIG         =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
```

This is probably a non-issue, but I figured I should bring it up just in case.

**Comment by yav** [comment]
The convention they use in RFC 5234 is that literal strings, such as `"A"`, are case insensitive, but in DaeDaLus `'A'` only refers to the upper case letter, which is why we need both cases.
